### ISSUE TITLE
Android: Get Maps API Key

### ISSUE THREAD

**Issue by molly-king** [poko/eat-ee#15]
from the google_maps_api.xml comments:

   To get one, follow this link, follow the directions and press "Create" at the end:

https://console.developers.google.com/flows/enableapi?apiid=maps_android_backend&keyType=CLIENT_SIDE_ANDROID&r=5F:76:6F:EB:2E:0A:AC:79:61:A3:D7:A8:5D:50:90:64:2C:D2:40:CE%3Bnet.ecoarttech.edibleecologies

```
You can also add your credentials to an existing key, using this line:
5F:76:6F:EB:2E:0A:AC:79:61:A3:D7:A8:5D:50:90:64:2C:D2:40:CE;net.ecoarttech.edibleecologies

Once you have your key (it starts with "AIza"), replace the "google_maps_key"
string in this file.
```

**Comment by molly-king** [comment]
Not sure if this is something I can do or if it has to be associated with your developer profile

**Comment by poko** [comment]
I got one setup with my account yesterday, but we will need to have Cary do
it with their official one and sub that in.

**Comment by poko** [comment]
Got Cary's api key. Added it to the release xml file.
